rsvp/urls.py
from django.urls import path
from . import views

app_name = 'rsvp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('menu/', views.menu, name='menu'),
    path('events/', views.events, name='events'),
    path('travel/', views.travel, name='travel'),
    path('registry/', views.registry, name='registry'),
    path('faqs/', views.faqs, name='faqs'),
    path('thank_you', views.thank_you, name='thank_you'),
    path('password', views.password, name='password')
]

wedding_website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rsvp.urls')),

]

rsvp/models.py
from django.db import models
from phone_field import PhoneField
from localflavor.us.models import USStateField
from localflavor.us.models import USZipCodeField


class Guest(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = USStateField(blank=True)
    zip = USZipCodeField(blank=True)
    email = models.EmailField(max_length=50)
    phone = PhoneField(blank=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

rsvp/forms.py
from django import forms

from .models import Guest


class GuestForm(forms.ModelForm):
    class Meta:
        model = Guest
        fields = ['name', 'address', 'city', 'state', 'zip', 'email', 'phone']
        labels = {
            'name': 'Name',
            'address': 'Address',
            'city': 'City',
            'state': 'State*',
            'zip': 'Zip Code*',
            'email': 'Email',
            'phone': 'Phone*',
        }


class PasswordForm(forms.Form):
    password = forms.CharField(label='Password', max_length=10)

rsvp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import GuestForm, PasswordForm
from lockdown.decorators import lockdown


@lockdown()
def index(request):
    if request.method != 'POST':
        form = GuestForm
    else:
        form = GuestForm(data=request.POST)
        if form.is_valid():
            new_guest = form.save(commit=True)
            return redirect('rsvp:thank_you')

    context = {'form': form}
    return render(request, 'rsvp/index.html', context)


@lockdown()
def menu(request):
    return render(request, 'rsvp/menu.html')


@lockdown()
def events(request):
    return render(request, 'rsvp/events.html')


@lockdown()
def travel(request):
    return render(request, 'rsvp/travel_accommodations.html')


@lockdown()
def registry(request):
    return render(request, 'rsvp/registry.html')


@lockdown()
def about_us(request):
    return render(request, 'rsvp/about_us.html')


@lockdown()
def faqs(request):
    return render(request, 'rsvp/faqs.html')


@lockdown()
def thank_you(request):
    return render(request, 'rsvp/thank_you.html')


def password(request):
    if request.method != 'POST':
        password_form = PasswordForm
    else:
        password_form = PasswordForm(data=request.POST)
        if password_form.is_valid():
            return redirect('rsvp:index')

    context = {'password_form': password_form}

    return render(request, 'rsvp/password.html', context)

rsvp/templates/rsvp/about_us.html
{% extends 'rsvp/base.html' %}
{% block content %}

<head>
    <title>About Us</title>

    <style>

         #pageHeading {
            color: #4D4C7D;
            text-align: center;
            font-family: Georgia;
            font-size: 5vw;
            /*border: solid #E9D5CA 4px;*/
            margin-top: 2%;
        }

        .nav-pills .nav-link.active {
            background-color: #4D4C7D;

        }


        .card {
        border: solid #E9D5CA 2px;

        }

        .d-block {
            max-width: 100%;
            width: 100%;
            height: auto;
            object-fit: contain;
        }

        .flex-container {
            display: flex;
            flex-direction: column;
            flex-wrap: nowrap;
            justify-content: flex-start;


        }

        .flex-child-left {
            order: 1;
        }

        .flex-child-right {
            order: 2;
            flex-basis: 10%;
            background-color: #E9D5CA;
            border-color: #E9D5CA;
            border-width: 2px;
            border-style: solid solid solid none;
            border-radius: 5px;
        }

    </style>

</head>

<div class="shadow p-3 mb-3 bg-body rounded" id="pageHeading">
  <div id="faqDiv"><h1><i>About Us</i></h1></div>
</div>

<div class="shadow p-3 mb-3 bg-body rounded" id="aboutUsShadow">

    <div class="flex-container" id="aboutUsContainer">

        <div class="flex-child-right" id="flexChildRight">

        </div>

        <div class="flex-child-left" id="flexChildLeft">

            <div class="d-flex align-items-start">
                <div class="nav flex-column nav-pills me-3" id="aboutUsTabs" role="tablist" aria-orientation="vertical">
                    <button class="nav-link active" id="aboutUsLizaTab" data-bs-toggle="pill" data-bs-target="#aboutUsLiza" type="button" role="tab" aria-controls="aboutUsLizaTab" aria-selected="true">Liza</button>
                    <button class="nav-link" id="aboutUsKyleTab" data-bs-toggle="pill" data-bs-target="#aboutUsKyle" type="button" role="tab" aria-label="aboutUsKyleTab" aria-selected="false">Kyle</button>
                    <button class="nav-link" id="aboutUsNellyTab" data-bs-toggle="pill" data-bs-target="#aboutUsNelly" type="button" role="tab" aria-label="aboutUsNellyTab" aria-selected="false">Nelly</button>
                    <button class="nav-link" id="aboutUsMooseTab" data-bs-toggle="pill" data-bs-target="#aboutUsMoose" type="button" role="tab" aria-labelledby="aboutUsMooseTab" aria-selected="false">Moose</button>
                </div>

                <div class="tab-content" id="aboutUsContent">
                    <div class="tab-pane fade show active" id="aboutUsLiza" role="tabpanel" aria-labelledby="aboutUsLizaTab">
                        <div class="card text-center" style="width: 15rem;">
                            <img src="https://i.ibb.co/7t4vYxF/FB-IMG-1657560610070.jpg" class="d-block w-100 rounded" alt="babeWithCake">
                            <div class="card-body">
                                <p>Liza description here.</p>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="aboutUsKyle" role="tabpanel" aria-labelledby="aboutUsKyleTab">
                        <div class="card text-center" style="width: 15rem">
                            <img src="https://i.ibb.co/MfG7F7P/FB-IMG-1657560584805.jpg" class="d-block w-100 rounded" alt="kyleWithPlants">
                            <div class="card-body">
                                <p>Kyle description here.</p>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="aboutUsNelly" role="tabpanel" aria-labelledby="aboutUsNellyTab">
                        <div class="card text-center" style="width: 15em">
                            <img src="https://i.ibb.co/2t5Bxp2/PXL-20220325-195201523-MP.jpg" class="d-block w-100 rounded" alt="nellyOnStand">
                            <div class="card-body">
                                <p>Nelly description here.</p>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="aboutUsMoose" role="tabpanel" aria-labelledby="aboutUsMooseTab">
                        <div class="card text-center" style="width: 15rem">
                            <img src="https://i.ibb.co/nCLwfmk/moose-in-bag.jpg" class="d-block w-100 rounded" alt="mooseInBag">
                            <div class="card-body">
                                <p>Moose description here.</p>
                            </div>
                        </div>
                    <div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock content %}

rsvp/templates/rsvp/base.html
{% load bootstrap5 %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <style>
      body {
          padding: 0 8vw;
      }

      #navMain {
          margin-left: 0.6vw;
          margin-right: 0.6vw;

      }

      .navbar-brand {
        font-family: Georgia;
        font-size: 1.8vw !important;
        font-weight: lighter;
        color: #E9D5CA !important;
      }

      .nav-link {
        font-family: Georgia;
        font-size: 1.4vw !important;
        color: #E9D5CA !important;
      }


      #main {
          display: flex;
          flex-flow: column nowrap;
          justify-content: center;
          align-items: center;
          min-height: 100vh;

      }

      #footer {
          font-family: Georgia;
          text-align: center;
          background-color: #363062;
          color: #E9D5CA;
          padding: 0.4vw 16vw;
          min-width: 48vw;
          width: 100%;
          margin-top: auto;
      }

      #monogram {
          max-width: 16vw;
          height: auto;
      }

     @media (max-width: 600px) {
        body {
            padding: 0;
        }

         #footer {
             min-width: 100vw;
         }

         #navMain {
          margin-left: 0;
          margin-right: 0;

      }

        .navbar-brand {
            font-size: 6.4vw !important;
        }

        .nav-link {
            font-size: 4.8vw !important;
        }

        #monogram {
          max-width: 24vw;
          height: auto;
      }

     }


  </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

<body>
  <nav id="navMain" class="navbar navbar-expand-lg" style="background-color: #363062;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'rsvp:index' %}" aria-current="page"><img id="monogram" src="https://i.ibb.co/wc8Zqkr/monogram-newest.png"></a>
    <button class="navbar-toggler" style="background-color: white; color: #E9D5CA;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'rsvp:menu' %}"><i>Menu</i></a>
        <a class="nav-link" href="{% url 'rsvp:events' %}"><i>Events</i><a>
        <a class="nav-link" href="{% url 'rsvp:travel' %}"><i>Travel</i></a>
        <a class="nav-link" href="{% url 'rsvp:registry' %}"><i>Registry</i></a>
<!--        <a class="nav-link" href="{% url 'rsvp:about_us' %}"><i>About Us</i></a>-->
        <a class="nav-link" href="{% url 'rsvp:faqs' %}"><i>FAQs</i></a>
      </div>
    </div>
  </div>
</nav>

    <main role="main" id="main" class="container-fluid">
        <div id="header">
            {% block page_header %}
            {% endblock page_header %}
        </div>

        <div id="content">
            {% block content %}{% endblock content %}
        </div>

        <div id="footer">
            {% block page_footer %}
            <small>Dr. Liza Ignatova & Kyle Montville, <br>&copy; 2022 - 2023</small>
            {% endblock page_footer %}
        </div>
    </main>

<!--HTML/BootStrap boilerplate-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
<!--HTML/BootStrap boilerplate-->

</body>
</html>

rsvp/templates/rsvp/events.html
{% extends 'rsvp/base.html' %}

{% block content %}

<head>
    <title>Events</title>

    <style>
        .zigzag-timeline__item {
                        /* Used to position the milestone */
                        position: relative;

                        /* Border */
                        border-bottom: 3px solid #71717a;
                        border-color: #E9D5CA;

                        /* Take full width */
                        width: 100%;
                    }

                    .zigzag-timeline__milestone {
                        /* Absolute position */
                        position: absolute;
                        top: 50%;

                        /* Circle it */
                        border-radius: 50%;
                        height: 2rem;
                        width: 2rem;

                        /* Misc */
                        background: #71717a;
                    }

                    /* Styles for even items */
                    .zigzag-timeline__item:nth-child(2n) {
                        border-left: 3px solid #71717a;
                        border-color: #E9D5CA;
                    }
                    .zigzag-timeline__item:nth-child(2n) .zigzag-timeline__milestone {
                        left: 0;
                        transform: translate(-50%, -50%);
                    }

                    /* Styles for odd items */
                    .zigzag-timeline__item:nth-child(2n + 1) {
                        border-right: 3px solid #71717a;
                        border-color: #E9D5CA;
                    }
                    .zigzag-timeline__item:nth-child(2n + 1) .zigzag-timeline__milestone {
                        right: 0;
                        transform: translate(50%, -50%);
                    }
        #pageHeading {
            color: #4D4C7D;
            text-align: center;
            font-family: Georgia;
            font-size: 5vw;
            padding-bottom: 1.8vw;
            margin: 2% 4%;
        }

        #overall {
                    font-family: Georgia;
                    text-align: center;

                    }

        #event_1 {
                    color: #827397;
                    }

        #event_1_desc {
                    color: #4D4C7D;
                    }

        #event_2 {
                    color: #827397;
                    }

        #event_2_desc {
                    color: #4D4C7D;
                    }

        #event_3 {color: #827397;
                    }

        #event_3_desc {
                    color: #4D4C7D;
                    }

        #event_4 {color: #827397;
                    }

        #event_4_desc {
                    color: #4D4C7D;
                    }

        #event_5 {color: #827397;
                    }

        #event_5_desc {
                    color: #4D4C7D;
                    }

        @media (max-width: 600px) {

         }

    </style>
</head>

<body>
<div class="" id="pageHeading">
  <div id="faqDiv"><h1><i>Schedule of Events</i></h1></div>
</div>

    <div id="Overall">
        <div class="zigzag-timeline__item">
                <div className="zigzag-timeline__milestone" id="event_1">
                    <h3>
                    <dl>
                        <dt>Informal Ceremony</dt>
                        <dt>4:00 pm - 5:00 pm</dt>
                    </dl>
                    </h3>
                </div>
                <p id="event_1_desc">Introductions, light music, speeches from guests and the couple.</p>
        </div>

        <div class="zigzag-timeline__item">

            <div className="zigzag-timeline__milestone" id="event_2">
                 <h3>
                    <dl>
                        <dt>Cocktail Hour</dt>
                        <dt>5:00 pm - 6:00 pm</dt>
                    </dl>
                    </h3>
            </div>
                <p id="event_2_desc">Appetizers, open bar, conversation, photography.</p>
        </div>


        <div class="zigzag-timeline__item">

            <div className="zigzag-timeline__milestone" id="event_3">
                <h3>
                    <dl>
                        <dt>Dinner</dt>
                        <dt>6:00 pm - 7:00 pm</dt>
                    </dl>
                </h3>
            </div>
                <p id="event_3_desc">Selection of main course dishes and desserts.</p>
        </div>

    <div class="zigzag-timeline__item">

        <div className="zigzag-timeline__milestone" id="event_4">
            <h3>
                <dl>
                    <dt>Dancing</dt>
                    <dt>7:00 pm - 9:00 pm</dt>
                </dl>
            </h3>
        </div>
            <p id="event_4_desc">Celebrate with dancing and music at your request!</p>
    </div>

    <div class="zigzag-timeline__item">

        <div className="zigzag-timeline__milestone" id="event_5">
            <h3>
                <dl>
                    <dt>Midnight Snack</dt>
                    <dt>9:00 pm - 10:00 pm</dt>
                </dl>
            </h3>
        </div>
            <p id="event_5_desc">Some light snacks for the road.</p>
    </div>
</div>

</body>

{% endblock content %}

rsvp/templates/rsvp/index.html
{% extends 'rsvp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<head>
    <title>Montova Celebration</title>

    <style>

        #overall {
            display: flex;
            flex-flow: row nowrap;
            font-family: Georgia;
            text-align: center;
            color: #827397;

        }

        #nameDiv {
            display: flex;
            flex-flow: row wrap;
            justify-content: center;
            align-items: center;
            color: #4D4C7D;
            background-color: white;
            font-size: 2vw;
            padding: 2vw 2vw;
        }

        #heart-img {
            min-width: 10vw;
            max-width: 16vw;
            height: auto;
            padding: 24px;
        }

        dt {
            font-size: 2vw;
        }

        .rounded {
            max-width: 100%;
            height: auto;
        }

        #pictureDiv {
            padding: 1.8vw 3.2vw;
        }

        #submitButton {
            color: #E9D5CA;
            background-color: #827397;
            border: none;
            border-color: #827397;
            border-radius: 8px;
            border-width: 2px;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        #formDiv p {
            font-size: 1.4vw;
            text-align: left;
            padding: 1.2vw 3.2vw;
        }

        #rsvpForm {
            font-size: 1.2vw;
        }

         @media (max-width: 600px) {
             #overall {
                 flex-flow: column nowrap;
                 font-size: 4vw;
             }

            #nameDiv {
                flex-flow: row wrap;
                margin: 0;
                font-size: 3.8vw;
            }

            dt {
                font-size: 6.4vw;
            }

            #heart-img {
            min-width: 8vw;
            max-width: 28vw;
            height: auto;
            padding: 24px;
            }

             #pictureDiv {
            padding: 4.8vw 1.2vw;
        }
             #formDiv p {
            font-size: 4.8vw;
        }

             #rsvpForm {
            font-size: 4.2vw;
        }

         }

    </style>
</head>

<div id="overall">

    <div class="shadow p-3 mb-3 bg-body rounded" id="titleDiv">
        <div class="shadow p-3 mb-2 rounded" id="nameDiv">
            <dt><i>Liza Ignatova<br>- & -<br>Kyle Montville</i></dt><br>
            <img id="heart-img" src="https://i.ibb.co/R2cFQvW/heart.jpg" alt="heart" border="0"><br>
            <br>
            <br><i>Wedding Celebration<br>
            Saturday, May 27th, 2023
            <br>
            <a href="https://barnardinn.com/" style="color: #4D4C70;" target="_blank" rel="noopener noreferrer">@The Barnard Inn</a></i>
        </div>
        <div id="pictureDiv">
            <p><img src="https://i.ibb.co/K73cFZP/babe-n-me.jpg" class="rounded">
            <p><h4><i>We would love for you to join us!</i></h4>
        </div>
    </div>

    <div class="shadow p-3 bg-body rounded" id="formDiv">
         <p><i>Please complete the form below as confirmation for each person who will be attending the event.</i></p>

        <form action="{% url 'rsvp:index' %}" method="post" class="form" id="rsvpForm">
            {% csrf_token %}
            {{ form|crispy }}
            <button  id="submitButton" name="submit">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

rsvp/templates/rsvp/password.html
{% extends 'rsvp/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<head>
    <title>Please enter password.</title>

    <style>

        div {
            text-align: center;
            font-family: Garamond;
            }

        h2 {
            margin-top: 30;
            }

        form {
            margin-top: 30;
            }

        button {
                color: white;
                background-color: pink;
                border-radius: 8px;
                border-width: 2px;
                margin-top: 20;
                margin-bottom: 20;
            }

    </style>
</head>

<div>
    <h2>Please enter the password to continue to the event website.</h2>

    <form action="{% url 'rsvp:password' %}" method="post" class="form">

        {% csrf_token %}
        {{ password_form|crispy }}

        <button name="submit">Submit</button>

    </form>
</div>

{% endblock content %}

rsvp/templates/rsvp/registry.html
{% extends 'rsvp/base.html' %}
{% block content %}

<head>
    <title>Registry</title>

    <style>

        #donateDiv {
            background-color: #4D4C7D;
            color: #E9D5CA;
            text-align: center;
            font-family: Georgia;
            font-size: 1.4vw;
        }

        #pageHeading {
            color: #4D4C7D;
            text-align: center;
            font-family: Georgia;
            font-size: 5vw;
            margin: 2% 4%;
        }

        .flex-container {
            display: flex;
            flex-flow: row nowrap;
            justify-content: center;
            align-items: flex-start;
            gap: 1.2vw;
        }

        .flex-child-top {
            flex: 1;
            text-align: center;
            font-family: Georgia;
            font-size: 1.2vw;
            color: #4D4C70;
        }

        #donateImg {
            padding: 0 1.6vw 1.6vw 1.6vw;
        }

        p {
            text-align: left;
        }



        .flex-child-bot {
            flex: 1;
            text-align: center;
            font-family: Georgia;
            font-size: 1.2vw;
            color: #4D4C70;
        }

        .flex-child-bot p{

        }

        @media (max-width: 600px) {
            .flex-container {
                flex-flow: column nowrap;
                align-items: center;
             }

            #donateImg {
                max-width: 64vw;
                height: auto;
                padding: 0 1.6vw 1.6vw 1.6vw;
            }

            #donateDiv {
                font-size: 4.8vw;
            }

            p {
                font-size: 4.2vw;
                padding: 4vw 6vw;
                margin-top: 2vw;
            }
         }

    </style>
</head>

<div class="" id="pageHeading">
  <div id="faqDiv"><h1><i>Registry</i></h1></div>
</div>

<div class="flex-container">
    <div class="flex-child-top">
        <div class="shadow p-3 mb-3 bg-body rounded">
            <div id="donateDiv">Help Us Relocate!</div>
            <br>
            <img id="donateImg" src="https://i.ibb.co/H2d87Mx/ggb-scaled.png" class="rounded-circle" alt="ggb-scaled">
<!--            <img src="https://i.ibb.co/5Lks5BK/beach-sc-scaled.jpg" class="rounded-circle" alt="beach-sc-scaled">-->
            <p>In lieu of a traditional registry, the couple will only be accepting donations to the moving fund,
            which will help them in their transition to their new lives on the west coast!</p>
        </div>
    </div>

    <div class="flex-child-bot">
        <div class="shadow p-3 mb-3 bg-body rounded">
            <div id="donateDiv" style="margin-bottom: 1.4vw;">GoFundMe</div>
            <div class="gfm-embed" data-url="https://www.gofundme.com/f/um46f-the-moving-fund/widget/large/"></div>
            <script defer src="https://www.gofundme.com/static/js/embed.js"></script>
            <p>While donations are never necessary, they are always welcome!</p>
        </div>
    </div>
</div>



{% endblock content %}

rsvp/templates/rsvp/thank_you.html
{% extends 'rsvp/base.html' %}

{% block content %}

<head>
    <title>Thank You</title>

    <style>
         #pageHeading {
            color: #4D4C7D;
            text-align: center;
            font-family: Georgia;
            font-size: 4vw;
            padding: 4.8vw;
        }

         @media (max-width: 600px) {
             #pageHeading {
                 font-size: 4.8vw;
                 padding: 10vw;
             }
         }
    </style>
</head>

<div id="pageHeading">
    <p>Thank you for RSVPing.</p>
    <p>We can't wait to see you!</p>
</div>

{% endblock content %}